'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Label} from '@/components/ui/label';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {ARCHIVE_KEY,LEGACY_KEY,readArchives,saveArchive,filterArchives,type ArchiveStore,type ChartArchive} from '@/lib/chart-archives';
import type {BaZiResult,BirthInput} from '@/lib/bazi';
export function ArchivePanel({result,onLoad,draftChanged}:{result:BaZiResult;onLoad:(input:BirthInput)=>void;draftChanged:boolean}) {
 const [store,setStore]=useState<ArchiveStore>({version:2,items:[]});const [ready,setReady]=useState(false);
 const [query,setQuery]=useState(''),[groupFilter,setGroupFilter]=useState('');
 const [editing,setEditing]=useState<string|null>(null),[title,setTitle]=useState(''),[group,setGroup]=useState(''),[note,setNote]=useState('');
 const [message,setMessage]=useState(''),[error,setError]=useState('');const [removed,setRemoved]=useState<ChartArchive|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(ARCHIVE_KEY);const next=readArchives(raw,localStorage.getItem(LEGACY_KEY));if(!raw)localStorage.setItem(ARCHIVE_KEY,JSON.stringify(next));setStore(next);setReady(true);}catch(e){setError(e instanceof Error?e.message:'无法读取档案。');}},[]);
 function persist(next:ArchiveStore){try{localStorage.setItem(ARCHIVE_KEY,JSON.stringify(next));setStore(next);setError('');return true;}catch{setError('设备存储不可用或空间不足，本次操作未保存。请释放空间后重试。');return false;}}
 function saveCurrent(){try{const now=new Date().toISOString();const next=saveArchive(store,{id:crypto.randomUUID(),title:title.trim()||result.input.name.trim()||'未署名命盘',group:group.trim(),note:note.trim(),input:{...result.input},createdAt:now,updatedAt:now});if(persist(next)){setMessage('当前已排命盘已存为新档案。');setEditing(null);}}catch(e){setError((e as Error).message);}}
 function edit(item:ChartArchive){setEditing(item.id);setTitle(item.title);setGroup(item.group);setNote(item.note);setMessage('正在编辑档案说明，出生资料保持该档案原值。');}
 function saveDetails(){const item=store.items.find(v=>v.id===editing);if(!item)return;try{if(persist(saveArchive(store,{...item,title:title.trim()||'未署名命盘',group:group.trim(),note:note.trim(),updatedAt:new Date().toISOString()}))){setEditing(null);setMessage('档案说明已更新。');}}catch(e){setError((e as Error).message);}}
 const shown=filterArchives(store.items,query,groupFilter),groups=[...new Set(store.items.map(v=>v.group).filter(Boolean))].sort();
 return <section className="panel space-y-6" aria-label="命盘档案"><div><h3 className="section-title">命盘档案</h3><p className="text-sm leading-7 text-muted-foreground">保存在当前浏览器，刷新后仍可使用；不会自动跨设备同步。原来的最近五份记录会迁入档案。</p></div>
 <div className="archive-editor space-y-4"><h4 className="font-medium">{editing?'编辑档案说明':'保存当前已排命盘'}</h4><p className="text-sm">当前命盘：{result.date} · {result.input.name||'未署名'} · {result.input.city}</p>{draftChanged&&<p className="text-sm text-primary">出生表单尚有修改。请先更新命盘，再保存新档案。</p>}<div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="archive-title">档案名称</Label><Input id="archive-title" maxLength={60} value={title} onChange={e=>setTitle(e.target.value)} placeholder={result.input.name||'例如：我的命盘'}/></div><div className="space-y-2"><Label htmlFor="archive-group">分组（选填）</Label><Input id="archive-group" maxLength={30} value={group} onChange={e=>setGroup(e.target.value)} placeholder="例如：家人、研究案例"/></div></div><Label htmlFor="archive-note">备注（选填）</Label><Textarea id="archive-note" maxLength={3000} value={note} onChange={e=>setNote(e.target.value)} placeholder="出生时刻来源、待复核的问题……"/><div className="flex flex-wrap gap-3">{editing?<><Button onClick={saveDetails} disabled={!ready}>保存档案说明</Button><Button variant="outline" onClick={()=>{setEditing(null);setTitle('');setGroup('');setNote('');}}>取消编辑</Button></>:<Button onClick={saveCurrent} disabled={!ready||draftChanged}>存为新档案</Button>}</div></div>
 <div className="grid gap-3 sm:grid-cols-[1fr_auto]"><div className="space-y-2"><Label htmlFor="archive-search">搜索档案</Label><Input id="archive-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="名称、备注或出生日期"/></div><div className="space-y-2"><Label htmlFor="archive-filter">筛选分组</Label><NativeSelect id="archive-filter" value={groupFilter} onChange={e=>setGroupFilter(e.target.value)}><NativeSelectOption value="">全部分组</NativeSelectOption>{groups.map(g=><NativeSelectOption key={g} value={g}>{g}</NativeSelectOption>)}</NativeSelect></div></div><p className="text-sm text-muted-foreground">共 {store.items.length} 份 · 当前显示 {shown.length} 份</p>
 <div className="space-y-3">{shown.map(item=><article key={item.id} className="archive-card"><div><h4 className="font-medium">{item.title}</h4><p className="text-sm leading-7 text-muted-foreground">{item.group||'未分组'} · {item.input.calendar==='lunar'?'农历':'公历'} {item.input.year}/{item.input.month}/{item.input.day}{item.input.leap?'（闰月）':''} · {item.input.unknownTime?'时刻未知':item.input.time} · {item.input.city}</p>{item.note&&<p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7">{item.note}</p>}</div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>onLoad({...item.input})}>打开命盘</Button><Button variant="ghost" onClick={()=>edit(item)}>编辑说明</Button><Button variant="ghost" onClick={()=>{if(persist({version:2,items:store.items.filter(v=>v.id!==item.id)})){setRemoved(item);if(editing===item.id)setEditing(null);setMessage('档案已删除，可撤销最近一次删除。');}}}>删除</Button></div></article>)}</div>{!shown.length&&<p className="rounded-xl border border-dashed p-6 text-center text-muted-foreground">{store.items.length?'没有匹配的档案，试试其他关键词。':'还没有档案，保存当前命盘开始使用。'}</p>}
 {removed&&<Button variant="outline" onClick={()=>{try{if(persist(saveArchive(store,removed))){setRemoved(null);setMessage('档案已恢复。');}}catch(e){setError((e as Error).message);}}}>撤销删除「{removed.title}」</Button>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{message&&<p role="status" className="text-sm">{message}</p>}</section>;
}
