'use client';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { ziweiPalaceEvidence, type ZiweiResult, type QimenResult } from '@/lib/metaphysics';

export function ZiweiDetails({ data, index, close }: { data: ZiweiResult; index: number | null; close: () => void }) {
  const evidence = index === null ? null : ziweiPalaceEvidence(data, index);
  return <Sheet open={!!evidence} onOpenChange={(open) => { if (!open) close(); }}><SheetContent className="overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{evidence?.palace.name} · 宫位依据</SheetTitle><SheetDescription>三方四正与四化分层查看，不把单星或化忌直接解释为事件。</SheetDescription></SheetHeader>{evidence && <div className="space-y-6 px-5 pb-8"><section><h4 className="mb-3 font-medium">三方四正</h4>{evidence.surrounded.map((p, i) => <p key={p.index} className="mb-3 text-sm leading-7">{['本宫','三合宫','三合宫','对宫'][i]} · {p.name} {p.heavenlyStem}{p.earthlyBranch}<br />{p.majorStars.map((s) => `${s.name}${s.mutagen ? `化${s.mutagen}` : ''}`).join('、') || '无主星'}</p>)}</section>{([{ name:'本命生年四化', rows:evidence.natal }, {name:'所选日期大限四化',rows:evidence.decadal}, {name:'所选日期流年四化',rows:evidence.yearly}]).map((group) => <section key={group.name}><h4 className="mb-3 font-medium">{group.name}</h4>{group.rows.length ? group.rows.map((r,i) => <p key={i} className="text-sm leading-7">{r.star} 化{r.transformation} → {r.palace}</p>) : <p className="text-sm text-muted-foreground">尚未计算该层资料。</p>}</section>)}</div>}</SheetContent></Sheet>;
}

export function QimenDetails({ data, number, close }: { data: QimenResult; number: number | null; close: () => void }) {
  const p = data.chart.jiuGongGe.find((p) => p.gong === number);
  const patterns = data.chart.classicPatterns.filter((r) => number !== null && r.palaces.includes(number));
  return <Sheet open={!!p} onOpenChange={(open) => { if (!open) close(); }}><SheetContent className="overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{p?.name} · 宫位依据</SheetTitle><SheetDescription>{data.time.replace('T',' ')} · 时家转盘拆补法</SheetDescription></SheetHeader>{p && <div className="space-y-5 px-5 pb-8"><p className="leading-8">门：{p.renPan.door || '无'}<br />星：{p.tianPan.star || '无'}<br />神：{p.shenPan.god || '无'}<br />天盘干：{p.tianPan.stem} · 地盘干：{p.diPan.stem}{p.tianPan.companionStar && <><br />随行：{p.tianPan.companionStar} {p.tianPan.companionStem}</>}</p><section><h4 className="font-medium">天地盘干关系</h4>{data.chart.stemRelations.filter((r) => r.gong === number).map((r,i) => <p key={i} className="mt-2 text-sm leading-7">{r.heavenStem} / {r.earthStem}：{r.relation} {r.pattern}</p>)}</section><section><h4 className="font-medium">此宫命中的传统格局</h4>{patterns.length ? patterns.map((r,i) => <p key={i} className="mt-3 text-sm leading-7">{r.name}：{r.summary}</p>) : <p className="mt-2 text-sm">未命中所列经典格局，不表示没有其他因素。</p>}</section><p className="text-sm text-muted-foreground">组合按宫位筛选。需要结合所问之事及其他宫位，不能把格局名称当作确定结果。</p></div>}</SheetContent></Sheet>;
}
