'use client';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { ziweiPalaceEvidence, type ZiweiResult, type QimenResult } from '@/lib/metaphysics';

type Layer = 'natal'|'decadal'|'yearly';
function Navigation({items,current,select,close}:{items:{id:number;name:string}[];current:number;select:(n:number)=>void;close:()=>void}) {
  const index=items.findIndex(p=>p.id===current);
  return <nav className="palace-navigation" aria-label="切换宫位"><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={()=>select(items[(index+items.length-1)%items.length].id)}>上一个宫位</Button><Button variant="outline" onClick={()=>select(items[(index+1)%items.length].id)}>下一个宫位</Button></div><Label htmlFor="detail-palace">直接选择宫位</Label><NativeSelect id="detail-palace" value={current} onChange={e=>select(Number(e.target.value))}>{items.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name}</NativeSelectOption>)}</NativeSelect><Button variant="outline" className="w-full" onClick={close}>返回命盘 · 保留高亮</Button></nav>;
}
export function ZiweiDetails({data,index,layer,onLayerChange,select,close}:{data:ZiweiResult;index:number|null;layer:Layer;onLayerChange:(v:Layer)=>void;select:(v:number)=>void;close:()=>void}) {
  const evidence=index===null?null:ziweiPalaceEvidence(data,index);
  return <Sheet open={!!evidence} onOpenChange={open=>{if(!open)close();}}><SheetContent className="palace-detail-sheet overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{evidence?.palace.name} · 宫位依据</SheetTitle><SheetDescription>三方四正与四化分层查看；切换宫位后，命盘同步高亮。</SheetDescription></SheetHeader>{evidence&&<div className="space-y-6 px-5 pb-8"><Navigation items={data.chart.palaces.map(p=>({id:p.index,name:p.name}))} current={evidence.palace.index} select={select} close={close}/><section><h4 className="mb-3 font-medium">三方四正</h4><div className="grid grid-cols-2 gap-2">{evidence.surrounded.map((p,i)=><button type="button" key={p.index} className="rounded-xl border p-3 text-left leading-7 hover:bg-accent focus-visible:outline-2" onClick={()=>select(p.index)}><strong>{['本宫','三合宫','三合宫','对宫'][i]} · {p.name}</strong><p>{p.heavenlyStem}{p.earthlyBranch}</p><p>{p.majorStars.map(s=>s.name).join('、')||'无主星'}</p></button>)}</div></section><section><Label htmlFor="detail-layer">四化层级</Label><NativeSelect id="detail-layer" value={layer} onChange={e=>onLayerChange(e.target.value as Layer)}><NativeSelectOption value="natal">本命四化</NativeSelectOption><NativeSelectOption value="decadal">所选日期大限四化</NativeSelectOption><NativeSelectOption value="yearly">所选日期流年四化</NativeSelectOption></NativeSelect><p className="my-3 text-sm leading-6">{layer==='natal'?'出生年四化':data.horoscope?.date+' 的运限四化'} · 以下列出该层四化在全盘的落宫。</p>{evidence[layer].length?evidence[layer].map((r,i)=><p key={i} className="rounded-lg bg-muted p-3 mb-2 leading-7">{r.star} 化{r.transformation} → {r.palace}</p>):<p className="leading-7">尚未计算该层资料。</p>}</section></div>}</SheetContent></Sheet>;
}
export function QimenDetails({data,number,select,close}:{data:QimenResult;number:number|null;select:(v:number)=>void;close:()=>void}) {
 const p=data.chart.jiuGongGe.find(p=>p.gong===number);
 const patterns=data.chart.classicPatterns.filter(r=>number!==null&&r.palaces.includes(number));
 return <Sheet open={!!p} onOpenChange={open=>{if(!open)close();}}><SheetContent className="palace-detail-sheet overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{p?.name} · 宫位依据</SheetTitle><SheetDescription>{data.time.replace('T',' ')} · 时家转盘拆补法</SheetDescription></SheetHeader>{p&&<div className="space-y-5 px-5 pb-8"><Navigation items={[4,9,2,3,5,7,8,1,6].flatMap(n=>{const p=data.chart.jiuGongGe.find(p=>p.gong===n);return p?[{id:n,name:p.name}]:[];})} current={p.gong} select={select} close={close}/><div className="grid grid-cols-2 gap-3">{[['门',p.renPan.door],['星',p.tianPan.star],['神',p.shenPan.god],['天盘干',p.tianPan.stem],['地盘干',p.diPan.stem],['随行',[p.tianPan.companionStar,p.tianPan.companionStem].filter(Boolean).join(' ')]].map(([label,value])=><p key={label} className="rounded-xl bg-muted p-3 leading-7"><span className="block text-sm text-muted-foreground">{label}</span>{value||'无'}</p>)}</div><section><h4 className="font-medium">天地盘干关系</h4>{data.chart.stemRelations.filter(r=>r.gong===number).map((r,i)=><p key={i} className="mt-2 leading-7">{r.heavenStem} / {r.earthStem}：{r.relation} {r.pattern}</p>)}</section><section><h4 className="font-medium">此宫命中的传统格局</h4>{patterns.length?patterns.map((r,i)=><p key={i} className="mt-3 leading-7">{r.name}：{r.summary}</p>):<p className="mt-2 leading-7">未命中所列经典格局，不表示没有其他因素。</p>}</section><p className="text-sm leading-7 text-muted-foreground">组合按宫位筛选，需要结合所问之事及其他宫位；格局名称不是确定结果。</p></div>}</SheetContent></Sheet>;
}
