'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Label} from '@/components/ui/label';
import {buildChartReport,type ChartReport,type ReportOptions} from '@/lib/chart-report';
import type {BaZiResult} from '@/lib/bazi';
import type {ZiweiResult,QimenResult} from '@/lib/metaphysics';
function ReportDocument({report,generated}:{report:ChartReport;generated:string}) {return <article className="report-document"><header><p className="report-brand">命笺 / MINGJIAN</p><h2>{report.title}</h2><p>{report.subtitle}</p><small>生成时间：{generated||'正在读取时间'} · 北京时间</small></header><div className="report-pillars">{report.pillars.map(p=><div key={p.label}><p>{p.label}</p><strong>{p.value}</strong><p>{p.detail}</p></div>)}</div>{report.sections.map((s,i)=><section key={i} className="report-section"><h3>{s.title}</h3>{s.lines.map((line,j)=><p key={j}>{line}</p>)}</section>)}</article>;}
export function ReportPanel({result,year,ziwei,qimen,draftChanged}:{result:BaZiResult;year:number;ziwei:ZiweiResult|null;qimen:QimenResult|null;draftChanged:boolean}) {
 const [options,setOptions]=useState<ReportOptions>({birth:false,details:false,ziwei:true,qimen:false});const [generated,setGenerated]=useState(''),[mounted,setMounted]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [imageUrl,setImageUrl]=useState(''),[textUrl,setTextUrl]=useState('');const generation=useRef(0);
 useEffect(()=>()=>{if(imageUrl)URL.revokeObjectURL(imageUrl);},[imageUrl]);
 useEffect(()=>()=>{if(textUrl)URL.revokeObjectURL(textUrl);},[textUrl]);
 const report=useMemo(()=>buildChartReport(result,year,ziwei,qimen,options),[result,year,ziwei,qimen,options]);
 useEffect(()=>{generation.current++;setBusy(false);setMounted(true);setImageUrl('');setTextUrl('');setGenerated(new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date()));setNotice('');return()=>{generation.current++;};},[report]);
 function textReport(){const lines=[report.title,report.subtitle,'生成时间：'+generated+' · 北京时间','',...report.pillars.map(p=>p.label+'：'+p.value+' · '+p.detail),...report.sections.flatMap(s=>['',s.title,...s.lines])];setTextUrl(URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/plain;charset=utf-8'})));setNotice('文字报告已准备好，点击下方链接保存。');}
 async function image(){const request=++generation.current;setBusy(true);try{const {downloadChartImage}=await import('@/lib/chart-image');const url=await downloadChartImage(report);if(request!==generation.current){URL.revokeObjectURL(url);return;}setImageUrl(url);setNotice('四柱图片已生成，可点击保存链接或长按图片。');}catch(e){if(request===generation.current)setNotice(e instanceof Error?e.message:'图片导出失败。');}finally{if(request===generation.current)setBusy(false);}}

 return <section className="panel space-y-5"><div><h3 className="section-title">报告导出</h3><p className="text-sm leading-7 text-muted-foreground">先选择内容并查看预览。PDF 使用浏览器打印窗口的“另存为 PDF”；图片仅包含四柱及基本口径。</p></div><div className="grid gap-4 sm:grid-cols-2">{([['birth','包含姓名与出生资料'],['details','包含详细依据'],['ziwei','包含当前紫微命盘'],['qimen','包含独立奇门盘']] as const).map(([key,label])=><div key={key} className="flex gap-3 items-center"><Checkbox id={'report-'+key} checked={options[key]} onCheckedChange={checked=>setOptions(v=>({...v,[key]:checked}))}/><Label htmlFor={'report-'+key}>{label}</Label></div>)}</div>{draftChanged&&<p className="text-sm text-primary">出生表单已修改，请先更新命盘。当前预览仍属于上次排盘。</p>}<div className="flex flex-wrap gap-3"><Button disabled={draftChanged||busy} onClick={()=>{window.print();setNotice('请在打印窗口选择“另存为 PDF”。如未弹出窗口，请用 Chrome / Edge 打开本站后打印。');}}>打印 / 保存为 PDF</Button><Button variant="outline" disabled={draftChanged||busy} onClick={image}>{busy?'正在生成图片…':'生成四柱图片 PNG'}</Button><Button variant="outline" disabled={draftChanged||busy} onClick={textReport}>生成文字报告</Button></div>{textUrl&&<a className="block text-primary underline" href={textUrl} download="命笺-命盘报告.txt">保存文字报告 TXT</a>}{notice&&<p role="status" className="text-sm">{notice}</p>}<p className="text-sm leading-7 text-muted-foreground">隐藏出生资料不会移除四柱本身。打印前可关闭浏览器的页眉页脚；取消打印不会生成文件。</p><>{imageUrl&&<div className="space-y-3"><a className="text-primary underline" href={imageUrl} download="命笺-四柱命盘.png">保存已生成的 PNG 图片</a><img src={imageUrl} alt="已生成的四柱命盘图片" width={1200} height={1100} className="w-full rounded-xl border"/></div>}</><div className="report-preview"><ReportDocument report={report} generated={generated}/></div>{mounted&&createPortal(<div className="report-print-root"><ReportDocument report={report} generated={generated}/></div>,document.body)}</section>;
}
