'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import type {BirthInput,BaZiResult} from '@/lib/bazi';
import type {TimeComparison,ComparisonRow} from '@/lib/time-comparison';
function Rows({rows}:{rows:ComparisonRow[]}){return <div className="space-y-3">{rows.map(r=><div key={r.label} className={'rounded-xl border p-4 '+(r.changed?'border-primary/40 bg-primary/5':'')}><h4 className="font-medium">{r.label} <span className="ml-2 text-sm text-muted-foreground">{r.changed?'不同':'相同'}</span></h4><div className="mt-2 grid gap-3 sm:grid-cols-2"><p className="text-sm leading-7 break-words"><strong>A</strong> · {r.a}</p><p className="text-sm leading-7 break-words"><strong>B</strong> · {r.b}</p></div></div>)}</div>;}
export function TimeComparisonPanel({result,targetDate,algorithm,draftChanged,onUse}:{result:BaZiResult;targetDate:string;algorithm:'default'|'zhongzhou';draftChanged:boolean;onUse:(input:BirthInput)=>void}){
 const [timeA,setTimeA]=useState(result.input.unknownTime?'09:00:00':result.input.time),[timeB,setTimeB]=useState('11:00:00');
 const [data,setData]=useState<TimeComparison|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[onlyChanges,setOnlyChanges]=useState(false);
 const generation=useRef(0);const key=JSON.stringify({input:result.input,timeA,timeB,targetDate,algorithm,draftChanged});
 useEffect(()=>{generation.current++;setData(null);setBusy(false);setError('');setNotice('');return()=>{generation.current++;};},[key]);
 async function compare(){const request=++generation.current;setBusy(true);setError('');try{const {compareBirthTimes}=await import('@/lib/time-comparison');const next=await compareBirthTimes(result.input,timeA,timeB,targetDate,algorithm);if(request===generation.current)setData(next);}catch(e){if(request===generation.current)setError(e instanceof Error?e.message:'对照未完成。');}finally{if(request===generation.current)setBusy(false);}}
 async function copy(){if(!data)return;const {comparisonText}=await import('@/lib/time-comparison');try{await navigator.clipboard.writeText(comparisonText(data));setNotice('对照结果已复制。');}catch{setNotice('当前浏览器不支持复制，请选择页面文字复制。');}}
 return <section className="panel space-y-5"><div><h3 className="section-title">双时辰对照</h3><p className="text-sm leading-7 text-muted-foreground">同一出生日期分别输入两个候选时刻，比较四柱、起运和紫微宫位。输入沿用出生资料的时间口径。</p></div><p className="rounded-xl bg-muted p-4 text-sm leading-7">出生日期：{result.date} · {result.input.city}<br/>换日：{result.input.daySect===1?'23:00':'00:00'} · {result.input.clock==='apparent'?'真太阳时':'北京时间'}<br/>紫微：{algorithm==='default'?'通行':'中州派'} · 运限日期 {targetDate}</p><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="candidate-a">候选 A 时刻</Label><Input id="candidate-a" type="time" step="1" value={timeA} onInput={e=>setTimeA(e.currentTarget.value)} onChange={e=>setTimeA(e.target.value)}/></div><div className="space-y-2"><Label htmlFor="candidate-b">候选 B 时刻</Label><Input id="candidate-b" type="time" step="1" value={timeB} onInput={e=>setTimeB(e.currentTarget.value)} onChange={e=>setTimeB(e.target.value)}/></div></div>{draftChanged&&<p role="status">出生资料已修改，请先更新命盘再对照。</p>}<Button onClick={compare} disabled={busy||draftChanged}>{busy?'正在计算两份命盘…':'生成双时辰对照'}</Button>{error&&<p role="alert" className="text-destructive">{error}</p>}{data&&<div className="space-y-5"><p className="font-medium">四柱中 {data.changedPillars} 柱不同；{data.palaceRows.length?'紫微 '+data.palaceRows.filter(r=>r.changed).length+' 项不同。':'紫微未生成。'}</p><div className="flex flex-wrap gap-2"><Button variant="outline" aria-pressed={onlyChanges} onClick={()=>setOnlyChanges(v=>!v)}>{onlyChanges?'显示全部结果':'只看不同项'}</Button><Button variant="outline" onClick={copy}>复制对照结果</Button></div><Rows rows={data.rows.filter(r=>!onlyChanges||r.changed)}/><h4 className="font-medium">紫微宫位与运限</h4>{onlyChanges&&data.palaceRows.length>0&&data.palaceRows.every(r=>!r.changed)&&<p className="text-sm">两份紫微结果相同，没有不同项。</p>}{data.palaceRows.length?<Rows rows={data.palaceRows.filter(r=>!onlyChanges||r.changed)}/>:data.candidates.map((c,i)=><p key={i} className="text-sm leading-7">候选 {i?'B':'A'}：{c.ziweiStatus}</p>)}<div className="flex flex-wrap gap-3">{data.candidates.map((c,i)=><Button key={i} variant="outline" onClick={()=>onUse({...c.birth.input})}>使用候选 {i?'B':'A'} 排盘</Button>)}</div><p className="text-sm text-muted-foreground">采用后可到“命盘档案”存为新档案。</p></div>}{notice&&<p role="status">{notice}</p>}</section>;
}
